name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: List all
      run: ls -la 
    - name: Get current directory
      run: pwd
    - name: Build the Docker image
      run: docker build -f Dockerfile --tag idiom-handler:$(date +%s)
